### ISSUE TITLE
Problem with granting WRITE_SECURE_SETTINGS permission

### ISSUE THREAD

**Issue by Adam4CZ** [bryan2894-playgrnd/SimpleWear#14]
Hello,

Recently I installed SimpleWear app and the add-on for settings and I ran into a problem with granting WRITE_SECURE_SETTINGS  secure permission to control some of the mobile settings.
When I run the batch script it gives some error and the secure permission is not granted as you can see on the screenshot.

![Screenshot 2023-03-06 102346](https://user-images.githubusercontent.com/15090021/223069517-eb883d67-fa94-468b-a71a-703a8e3e8380.png)

I have OnePlus Nord 2T 5G with OS version Oxygen OS 12.1 based on Android 12.

![Screenshot 2023-03-06 102445](https://user-images.githubusercontent.com/15090021/223069564-cfe89bcf-4865-4b2c-af46-0040c45ea9c5.png)
![Screenshot_2023-03-06-10-22-17-12_9492aa3750dca76abb7c25b39a5f1e8e](https://user-images.githubusercontent.com/15090021/223069576-6057ee5e-748a-4c40-87f0-577188aa6cbc.jpg)

Is there any update or solution for this problem?
Thank you.

The issue is probably the same as closed #4

**Comment by Adam4CZ** [comment]
Today I tried it also on the new version but still the same issue

![Screenshot 2023-03-10 163154](https://user-images.githubusercontent.com/15090021/224358115-3f96e679-a428-48ab-8514-654949f5ef1a.png)
![Screenshot_2023-03-10-16-34-22-44_9492aa3750dca76abb7c25b39a5f1e8e](https://user-images.githubusercontent.com/15090021/224358127-d0c6c9db-7b45-4cbe-946c-627aa2da77fa.jpg)

**Comment by mcfasa09** [comment]
Same issue on a Galaxy Watch 4 connected to a Pixel 7.

**Comment by McFaul4** [comment]
Same Issue with my Galaxy watch 4 Classic LTE connected to the One Plus Nord

**Comment by VeraPush** [comment]
I have an able write secure problem ... . Can you help

**Comment by Aradig26** [comment]
Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 11218 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
	at android.app.ContextImpl.enforce(ContextImpl.java:2359)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2387)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1384)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1366)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:599)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2604)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:309)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7140)
	at android.os.Binder.shellCommand(Binder.java:1085)
	at android.os.Binder.onTransact(Binder.java:903)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7124)
	at android.os.Binder.execTransactInternal(Binder.java:1321)
	at android.os.Binder.execTransact(Binder.java:1280)

**Comment by thewizrd** [comment]
Please check if you have one of the following settings in Developer options and enable it:

- USB debugging (Security settings)
- Disable Permission Monitoring

Lastly, reboot and try again

**Comment by Jprussell2020** [comment]
Hi  i want to inscribe pls.thank you

**Comment by Adam4CZ** [comment]
> Please check if you have one of the following settings in Developer options and enable it:
> 
>     * USB debugging (Security settings)
> 
>     * Disable Permission Monitoring
> 
> 
> Lastly, reboot and try again

Yes, it worked. Thank you so much
